database:
  mysql:
    ip4: 127.0.0.1
    ip6: "::1"
    port: 3306
    socket: /var/run/mysqld/mysqld.sock
    root:
      user: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65376164346431303234613763316236373031353465373066613161646530626163373663396663
        3831383832323133316238396564653362383461333133320a663636336235376364643464393735
        65333566643366316531323434353762366436393938323238353761316632653738316235386562
        6537303336353262630a393666323361306462393737616332613664356231353132366364393064
        3335
      password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65303432373430366139646637653136346464333733396265623033356363383535363761633539
        3561333264343731383765393839303634376462636430640a323532303765383534663539396363
        37366136663165393637356164303435366262623066643235636238666132653639346663356164
        3364623233363630350a323939326264613135613337653963306161356563396333616333633263
        61353433313333303734316234343433613062633536366133346535626263613564
  redis:
    ip4: 127.0.0.1
    ip6: "::1"
    port: 6379
    databases: 16
